import type { Metadata } from 'next';
import Link from 'next/link';

import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { ThemeProvider } from '@/app/components/theme-provider';
import { NavLink } from '@/app/components/nav-link';
import { ModeToggle } from '@/app/components/mode-toggle';

import '@/app/globals.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container mx-auto min-h-screen p-4">
            <header className="fixed inset-x-0 top-0 z-50 bg-background/75 px-4 py-6 backdrop-blur-sm">
              <div className="container mx-auto flex items-center justify-between">
                <Link href="/">
                  <h1>RN</h1>
                </Link>
                <nav>
                  <ul className="flex gap-10">
                    <li>
                      <NavLink href="/">Home</NavLink>
                    </li>
                    <li>
                      <NavLink href="/projects">Projects</NavLink>
                    </li>
                    <li>
                      <NavLink href="/contact">Contact</NavLink>
                    </li>
                  </ul>
                </nav>
                <ModeToggle />
              </div>
            </header>
            <main className="mt-[calc(theme(spacing.6)*2+theme(fontSize.base)*1.5+40px)]">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
