import type { Metadata } from 'next';

import { Inter, Playfair_Display, Ubuntu_Sans_Mono } from 'next/font/google';
import { Header } from '@/app/components/header';
import { Providers } from '@/app/components/providers';
import { cn } from '@/lib/utils';
import { Footer } from '@/app/components/footer';

import '@/app/globals.css';
import { getDictionary } from '@/get-dictionary';
import { Locale } from '@/i18n-config';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
});
const ubuntu = Ubuntu_Sans_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
  const dict = await getDictionary(lang);
  return (
    <html
      lang="en"
      className="overflow-y-scroll scroll-smooth"
      suppressHydrationWarning
    >
      <body
        className={cn(
          'flex min-h-screen flex-col font-sans antialiased',
          inter.variable,
          playfair.variable,
          ubuntu.variable,
        )}
      >
        <Providers>
          <Header dict={dict.menuItems} />
          <main className="grow">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
